# Generated by Django 2.1.15 on 2020-03-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
