# Generated by Django 2.1.15 on 2020-03-01 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0002_remove_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtype', models.CharField(max_length=2)),
                ('gid', models.CharField(max_length=10)),
                ('gname', models.CharField(max_length=50)),
                ('pid', models.CharField(max_length=10)),
                ('seq', models.IntegerField(null=True)),
                ('data', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
