# Generated by Django 2.1.15 on 2020-03-01 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0003_urldb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtype', models.CharField(max_length=2)),
                ('gid', models.CharField(max_length=10)),
                ('gname', models.CharField(max_length=50)),
                ('pid', models.CharField(max_length=10)),
                ('seq', models.IntegerField(null=True)),
                ('data', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=256)),
                ('file_name', models.CharField(max_length=256)),
                ('file_path', models.CharField(max_length=512)),
                ('desc', models.TextField()),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('valid_start', models.DateTimeField()),
                ('valid_end', models.DateTimeField(null=True)),
                ('desc', models.CharField(max_length=512, null=True)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
