# Generated by Django 2.1.15 on 2020-03-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0004_category_urlfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlfile',
            name='file_key',
            field=models.CharField(default='0000', max_length=50),
        ),
        migrations.AddField(
            model_name='urlfile',
            name='file_ver',
            field=models.CharField(default='0.0.1', max_length=50),
        ),
        migrations.AlterField(
            model_name='urlfile',
            name='file_type',
            field=models.CharField(max_length=10),
        ),
    ]
