# Generated by Django 2.1.15 on 2020-03-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0005_auto_20200302_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlfile',
            name='file_type',
            field=models.CharField(default='full', max_length=10),
        ),
    ]
