# Generated by Django 2.1.15 on 2020-04-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0007_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='published_at',
        ),
    ]
