# Generated by Django 2.1.15 on 2020-04-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0009_user_file_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dtype',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='urldb',
            name='dtype',
            field=models.IntegerField(null=True),
        ),
    ]
