# Generated by Django 2.1.15 on 2020-04-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0010_auto_20200429_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dtype',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='urldb',
            name='dtype',
            field=models.IntegerField(default=1),
        ),
    ]
