# Generated by Django 2.1.15 on 2020-04-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0012_auto_20200429_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldb',
            old_name='mod_at',
            new_name='mod_date',
        ),
        migrations.RenameField(
            model_name='urldb',
            old_name='reg_at',
            new_name='reg_date',
        ),
    ]
