# Generated by Django 2.1.15 on 2020-05-01 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0013_auto_20200429_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldb',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='urldb',
            name='mod_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
