# Generated by Django 2.1.15 on 2020-05-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0014_auto_20200501_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldb',
            name='mod_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
