# Generated by Django 2.1.15 on 2020-05-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0015_auto_20200501_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldb',
            old_name='desc',
            new_name='description',
        ),
    ]
