# Generated by Django 2.1.15 on 2020-05-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0017_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='affected_rows',
            field=models.IntegerField(default=0),
        ),
    ]
