# Generated by Django 2.1.15 on 2020-05-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0018_checkpoint_affected_rows'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='urlfile',
            index=models.Index(fields=['reg_date'], name='reg_date_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['file_key'], name='file_key_idx'),
        ),
    ]
