# Generated by Django 2.1.15 on 2020-05-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0019_auto_20200505_0722'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['reg_date'], name='reg_date_idx'),
        ),
    ]
