# Generated by Django 2.1.15 on 2020-05-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0020_auto_20200505_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.TextField(null=True),
        ),
    ]
