# Generated by Django 2.1.15 on 2020-05-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0021_post_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='salt_key',
            field=models.CharField(default='dalbit-x', max_length=20),
        ),
    ]
