# Generated by Django 2.1.15 on 2020-07-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalbit', '0022_checkpoint_salt_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldb',
            old_name='data',
            new_name='host',
        ),
        migrations.AddField(
            model_name='urldb',
            name='path',
            field=models.CharField(default='/', max_length=256),
        ),
        migrations.AddField(
            model_name='urldb',
            name='port',
            field=models.CharField(default='80', max_length=256),
        ),
    ]
